/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SandboxEvidenceJs {
  protocolVersion: number
  active: boolean
  backend: string
  policySha256: string
  sandboxPid: number
  effectiveReadRootsHash?: string
  effectiveWriteRootsHash?: string
  warnings: Array<string>
}
export interface EnvPair {
  key: string
  value: string
}
export interface LaunchSandboxOptions {
  policyJson: string
  command: string
  args: Array<string>
  cwd: string
  env?: Array<EnvPair>
  readRoots?: Array<string>
  writeRoots?: Array<string>
}
export declare function preflight(): void
export declare function resolveHelperPath(): string
export declare function helperVersion(): string
export declare function runSelfTest(): void
export declare function windowsSetupStatus(sandboxHome?: string | undefined | null): boolean
export declare function windowsSetup(nodeExe: string, setupScript: string, runnerScript: string, sandboxHome: string, policyCwd: string): void
export declare function runSetupHelper(payloadB64: string): void
export declare function runCommandRunner(args: Array<string>): void
export declare function launchSandboxedWorker(options: LaunchSandboxOptions): SandboxChild
export declare class SandboxChild {
  get pid(): number
  get evidence(): SandboxEvidenceJs
  waitForAttestation(timeoutMs?: number | undefined | null): boolean
  writeStdin(data: Buffer): void
  endStdin(): void
  readStdoutChunk(maxBytes?: number | undefined | null): Buffer
  readStderrChunk(maxBytes?: number | undefined | null): Buffer
  kill(): void
  pollExit(): number | null
  wait(): number
  close(): void
}
